all: 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
all: 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
all: 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
all: 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
all: 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
