 
 
brennanb_corr.o: brennanb_corr.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

brennanb_stats.o: brennanb_stats.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

all: brennanb_corr.o brennanb_stats.o 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
 
 
brennanb_corr.o: brennanb_corr.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

brennanb_stats.o: brennanb_stats.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

all: brennanb_corr.o brennanb_stats.o 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
 
 
brennanb_corr.o: brennanb_corr.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

brennanb_stats.o: brennanb_stats.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

all: brennanb_corr.o brennanb_stats.o 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
 
 
brennanb_corr.o: brennanb_corr.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

brennanb_stats.o: brennanb_stats.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

all: brennanb_corr.o brennanb_stats.o 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
 
 
brennanb_corr.o: brennanb_corr.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

brennanb_stats.o: brennanb_stats.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

all: brennanb_corr.o brennanb_stats.o 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
 
 
brennanb_corr.o: brennanb_corr.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

brennanb_stats.o: brennanb_stats.cpp
	 	 	 g++ -c $^
	 	 	 g++ -o Multimain $^

all: brennanb_corr.o brennanb_stats.o 

clean: 
	 rm -f *.o
	 rm -f *.gch
	 rm -f all
